# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817d75de6713d7bb908494d471a25f05a37d02624f3259ac0c25b598d1b594619e45e534480b88310eb6905ec7ce52b40f59d384130942420a27fc47f245055a

test:
  secret_key_base: 46bb342814303254ed9b0e86229cac28cbfa137f760f71ce0c9c973c29c4e23ce1da2d2b4ffe086323424464e2bc7a81edb23c8f8e4aee9a944cbe63c0882346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
